name: CI
on:
  push:
    branches:
      - main
jobs:
              
  mysql:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: test
        run: |
        
          set -x
          
          docker run --detach --env MYSQL_ROOT_PASSWORD=password --name mysql --volume ${PWD}/script.sql:/docker-entrypoint-initdb.d/script.sql:ro mysql:latest
          
          while true
            do
              sleep 10
              docker logs mysql 2>& 1 | grep "ready for connections" && break
            done
          
          docker logs mysql 2>& 1 | grep ERROR && exit 100
          
          docker logs mysql
